### ISSUE TITLE
Mod broken after update (VRC Build 1169)

### ISSUE THREAD

**Issue by Preta-Crowz** [DragonPlayerX/ScreenshotManager#10]
![image](https://user-images.githubusercontent.com/16697820/155632803-5c6b09be-41c3-4006-9912-f8dc1b638c2a.png)
Panel is drown over menu and not disappear.

**Comment by DragonPlayerX** [comment]
Incompatibility with VRChat build 1169 was fixed in commit 7a8f06d94ef0f3afa1708b0796b68cef4d9089b1 and included in release [Screenshot Manager 2.4.0](https://github.com/DragonPlayerX/ScreenshotManager/releases/tag/2.4.0).
