### ISSUE TITLE
Custom Webhooks

### ISSUE THREAD

**Issue by MrDj200** [DragonPlayerX/ScreenshotManager#13]
Hey there, 

I wanted to make a software running on my server that converts pictures I send to it to webp, and uses it's compression to retain a higher quality, since jpeg is not the best at keeping quality.
However, I can't seem to put in any other URL's than Discord Webhooks.
Would it be possible to allow for custom URL's? Maybe with a setting to enable it per webhook or per client.

The reason I wouldn't want the webp conversion to happen on my pc is that it's very resource intensive, and would probably not result in the best experience while in VR (especially on my potato pc)

**Comment by DragonPlayerX** [comment]
I can implement that yes, but the web request will be in the format of a discord webhook so you would have to deal with it on your custom endpoint then. Of course you also should send a successful response back to the mod otherwise it would throw an exception.

**Comment by DragonPlayerX** [comment]
Custom webhook urls were added in commit https://github.com/DragonPlayerX/ScreenshotManager/commit/bc11b79742acd9cb4dded9d07881f0039c09c143 and included in release [Screenshot Manager 2.4.3](https://github.com/DragonPlayerX/ScreenshotManager/releases/tag/2.4.3).
