### ISSUE TITLE
Use Discord Time Stamps

### ISSUE THREAD

**Issue by MrDj200** [DragonPlayerX/ScreenshotManager#2]
Hey, love the mod, I'd love if it could make use of the discord timestamps.

Not really documentation, but should be enough to explain what I mean:
https://hammertime.djdavid98.art/en-GB

Maybe have the option to type something like `Timestamp:d` where `d` would do the same as shown above.
Should be quite easy :)

**Comment by DragonPlayerX** [comment]
Thanks for the great feedback. ^^

I will add this to my todo list for this mod, it's a nice addition. But first i have to focus on the new VRChat UI update.

**Comment by DragonPlayerX** [comment]
The timestamp functions are implemented and will be available as soon as the VRChat update goes live.
