### ISSUE TITLE
trouble with compression threshold

### ISSUE THREAD

**Issue by MexyACJ** [DragonPlayerX/ScreenshotManager#7]
i use the mod "camera res changer" to take pictures in 8k 
and i dont really understand the compression threshold part i set it to my servers limit because its a level 2 discord server i should be able to upload them cause none of the pictures come up to reaching that limit even tho they are 8k but it keeps throwing errors when i try 
and ive add the compression threshold line and ive put it to 50 for 50 MB but still doesn't work i put it to 20 for 20 MB and all pictures come in super small size and lower quality when your description even says to type the desired size and it will make it to MB but it doesnt 
thats why im confused

**Comment by DragonPlayerX** [comment]
Can you please show me your Webhook Config files (hide the token) and the logs or pictures with errors?

**Comment by MexyACJ** [comment]
![image](https://user-images.githubusercontent.com/44936753/143215952-2896a85e-7f5c-4183-aa09-06ac9d8a417e.png)
![image](https://user-images.githubusercontent.com/44936753/143216241-4e1c6887-c3d1-4ab8-9343-fb7eabbceaf7.png)

**Comment by MexyACJ** [comment]
i took off the threshold line, thinking it was going to work but didnt

**Comment by DragonPlayerX** [comment]
Could you add me on Discord (DragonPlayer#3365) for further discussion?
