### ISSUE TITLE
Buttons coming out of quick menu at an angle (see screenshot)

### ISSUE THREAD

**Issue by forever-and-a-day** [DragonPlayerX/ScreenshotManager#9]
![20220108134557_1](https://user-images.githubusercontent.com/10383240/148661134-4dd8ef4c-7972-432c-95c8-6e27a81dccc1.jpg)
![20220108134611_1_vr](https://user-images.githubusercontent.com/10383240/148661143-18296584-452a-452d-b15a-f15c8993527b.jpg)

The buttons are still clickable as if they were in their original location. Let me know if you need logs. Thanks!

**Comment by DragonPlayerX** [comment]
Does it always happen in VR? I had another report for that a while ago but i couldn't replicate it or it maybe only occurs rarely.

**Comment by forever-and-a-day** [comment]
Hmmm.... I had it every time I started VRC yesterday, but It went away today, so I assumed you patched it lol. Sorry I can't be of more help :(
As I can't reproduce this error, feel free to close the issue. My modlist is kinda high, so it might've been something else.

**Comment by DragonPlayerX** [comment]
I guess it only happens really rare when playing with VR when the controller is rotating the menu. So i'll try to fix it with the next release, but because of the fact that i can't reproduce it, i can't make sure that the fix works properly.
